### ISSUE TITLE
There is some error after selecting video!

### ISSUE THREAD

**Issue by shubhwicked** [wuapnjie/VideoSplit#1]
After selecting video, it starts rendering something and after reaching at 47, this problem occur. I am attaching the logcat.

`07-20 10:48:01.189 14352-14498/com.xiaopo.flying.videosplit E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                                              Process: com.xiaopo.flying.videosplit, PID: 14352
                                                                              java.lang.IllegalStateException: Failed to stop the muxer
                                                                                  at android.media.MediaMuxer.nativeStop(Native Method)
                                                                                  at android.media.MediaMuxer.stop(MediaMuxer.java:447)
                                                                                  at com.xiaopo.flying.videosplit.mix.AVMixingTask.mixAV(AVMixingTask.java:68)
                                                                                  at com.xiaopo.flying.videosplit.mix.AVMixingTask.run(AVMixingTask.java:32)
                                                                                  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
                                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                                  at java.lang.Thread.run(Thread.java:764)
07-20 10:48:01.776 14352-14352/com.xiaopo.flying.videosplit E/WindowManager: android.view.WindowLeaked: Activity com.xiaopo.flying.demo.MainActivity has leaked window DecorView@6c8fa70[] that was originally added here
                                                                                 at android.view.ViewRootImpl.<init>(ViewRootImpl.java:485)
                                                                                 at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:346)
                                                                                 at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
                                                                                 at android.app.Dialog.show(Dialog.java:330)
                                                                                 at com.xiaopo.flying.demo.MainActivity.startMix(MainActivity.java:107)
                                                                                 at com.xiaopo.flying.demo.MainActivity.bridge$lambda$0$MainActivity(Unknown Source:0)
                                                                                 at com.xiaopo.flying.demo.MainActivity$$Lambda$0.onClick(Unknown Source:21)
                                                                                 at android.view.View.performClick(View.java:6294)
                                                                                 at android.view.View$PerformClick.run(View.java:24770)
                                                                                 at android.os.Handler.handleCallback(Handler.java:790)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                 at android.os.Looper.loop(Looper.java:164)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
`

**Comment by wuapnjie** [comment]
This project is not finish. I write a hard code for audio path, you should change it.
